Sitefinity/feather-samples

SimpleContentBlock/Mvc/Controllers/SimpleContentBlockController.cs, SimpleContentBlock/Mvc/Scripts/SimpleContentBlock/designerview-simple.js, SimpleContentBlock/Mvc/Views/SimpleContentBlock/DesignerView.Simple.cshtml, SimpleContentBlock/Mvc/Views/SimpleContentBlock/DesignerView.Simple.json, SimpleContentBlock/Mvc/Views/SimpleContentBlock/custom-html-field-template.sf-cshtml, SimpleContentBlock/OpenAccessNuGet.targets, SimpleContentBlock/Properties/AssemblyInfo.cs, SimpleContentBlock/SimpleContentBlock.csproj, SimpleContentBlock/app.config, SimpleContentBlock/packages.config
=> Content block widget

AttributeRouting/AttributeRoutingSamples.sln, AttributeRouting/BooksWidget/BooksWidget.csproj, AttributeRouting/BooksWidget/Mvc/Controllers/BooksController.cs, AttributeRouting/BooksWidget/Mvc/Models/Book.cs, AttributeRouting/BooksWidget/Mvc/Models/BooksViewModel.cs, AttributeRouting/BooksWidget/Mvc/Scripts/books-widget.js, AttributeRouting/BooksWidget/Mvc/Views/Books/Index.cshtml, AttributeRouting/BooksWidget/Properties/AssemblyInfo.cs, AttributeRouting/BooksWidget/app.config, AttributeRouting/BooksWidget/packages.config
=> attribute routing sample

DevMagazineSite/SitefinityWebApp/App_Data/Sitefinity/Configuration/DataConfig.config
=> Reverted connection string to original

AttributeRouting/BooksWidget/BooksWidget.csproj, AttributeRouting/BooksWidget/packages.config
=> Upgraded to 8.2

ReCaptcha/ReCaptcha.sln, ReCaptcha/ReCaptcha.sln.GhostDoc.xml, ReCaptcha/ReCaptcha/Initializer.cs, ReCaptcha/ReCaptcha/InterfaceMappings.cs, ReCaptcha/ReCaptcha/Mvc/Controllers/RecaptchaController.cs, ReCaptcha/ReCaptcha/Mvc/Models/IRecaptchaModel.cs, ReCaptcha/ReCaptcha/Mvc/Models/RecaptchaModel.cs, ReCaptcha/ReCaptcha/Mvc/Models/RecaptchaViewModel.cs, ReCaptcha/ReCaptcha/Mvc/Scripts/Recaptcha/designerview-simple.js, ReCaptcha/ReCaptcha/Mvc/Scripts/Recaptcha/recaptcha.js, ReCaptcha/ReCaptcha/Mvc/StringResources/RecaptchaResources.cs, ReCaptcha/ReCaptcha/Mvc/Views/Recaptcha/DesignerView.Simple.cshtml, ReCaptcha/ReCaptcha/Mvc/Views/Recaptcha/DesignerView.Simple.json, ReCaptcha/ReCaptcha/Mvc/Views/Recaptcha/Write.Default.cshtml, ReCaptcha/ReCaptcha/Properties/AssemblyInfo.cs, ReCaptcha/ReCaptcha/ReCaptcha.csproj, ReCaptcha/ReCaptcha/app.config, ReCaptcha/ReCaptcha/packages.config
=> recaptcha sample

AttributeRouting/BooksWidget/BooksWidget.csproj, AttributeRouting/BooksWidget/packages.config, KendoBooksWidget/KendoBooksWidget.sln, KendoBooksWidget/KendoBooksWidget/KendoBooksWidget.csproj, KendoBooksWidget/KendoBooksWidget/Mvc/Controllers/KendoBooksController.cs, KendoBooksWidget/KendoBooksWidget/Mvc/Models/Book.cs, KendoBooksWidget/KendoBooksWidget/Mvc/Models/BooksViewModel.cs, KendoBooksWidget/KendoBooksWidget/Mvc/Scripts/kendo-books-widget.js, KendoBooksWidget/KendoBooksWidget/Mvc/Views/KendoBooks/Index.cshtml, KendoBooksWidget/KendoBooksWidget/Properties/AssemblyInfo.cs, KendoBooksWidget/KendoBooksWidget/app.config, KendoBooksWidget/KendoBooksWidget/packages.config, KendoBooksWidget/README.md
=> Kendo sample

OverridingDefaultDesigners/AddingAdditionalClientComponents/SitefinityWebApp/Mvc/Scripts/News/designerview-simple.js, OverridingDefaultDesigners/AddingAdditionalClientComponents/SitefinityWebApp/Mvc/Views/News/DesignerView.Simple.cshtml, OverridingDefaultDesigners/AddingAdditionalClientComponents/SitefinityWebApp/Mvc/Views/News/DesignerView.Simple.json, OverridingDefaultDesigners/AddingAdditionalScript/SitefinityWebApp/Mvc/Scripts/News/my-custom-script.js, OverridingDefaultDesigners/AddingAdditionalScript/SitefinityWebApp/Mvc/Views/News/DesignerView.Simple.json, OverridingDefaultDesigners/AddingCustomAngularJSModule/SitefinityWebApp/Mvc/Scripts/News/designerview-simple.js, OverridingDefaultDesigners/AddingCustomClientSideLogic/SitefinityWebApp/Mvc/Scripts/News/designerview-simple.js, OverridingDefaultDesigners/RemovingClientComponent/SitefinityWebApp/Mvc/Views/News/DesignerView.Simple.cshtml, OverridingDefaultDesigners/RemovingClientComponent/SitefinityWebApp/Mvc/Views/News/DesignerView.Simple.json
=> Added samples

README.md
=> Contributing section added to readme

CustomStylesContentBlock/SitefinityWebApp/client-components/fields/html-field/sf-html-field.sf-cshtml, CustomStylesContentBlock/readme.md
=> Custom styles editor and readme

SimpleContentBlock/readme.md
=> Documentation for Content block toolbar alter added

BoldlessContentBlock/SitefinityWebApp/client-components/fields/html-field/sf-html-field.sf-cshtml, BoldlessContentBlock/readme.md
=> Content block boldless

SingleDynamicContent/README.md, SingleDynamicContent/SingleDynamicContent.sln, SingleDynamicContent/SingleDynamicContent/Mvc/Controllers/SingleDynamicContentController.cs, SingleDynamicContent/SingleDynamicContent/Mvc/Models/SingleDynamicContentModel.cs, SingleDynamicContent/SingleDynamicContent/Mvc/Scripts/SingleDynamicContent/designerview-simple.js, SingleDynamicContent/SingleDynamicContent/Mvc/Views/SingleDynamicContent/Default.cshtml, SingleDynamicContent/SingleDynamicContent/Mvc/Views/SingleDynamicContent/DesignerView.Simple.cshtml, SingleDynamicContent/SingleDynamicContent/Mvc/Views/SingleDynamicContent/DesignerView.Simple.json, SingleDynamicContent/SingleDynamicContent/OpenAccessNuGet.targets, SingleDynamicContent/SingleDynamicContent/Properties/AssemblyInfo.cs, SingleDynamicContent/SingleDynamicContent/SingleDynamicContent.csproj, SingleDynamicContent/SingleDynamicContent/app.config, SingleDynamicContent/SingleDynamicContent/packages.config
=> Single dynamic item

AttributeRouting/BooksWidget/Properties/AssemblyInfo.cs, AuthorWidget/AuthorWidget/Properties/AssemblyInfo.cs, CustomImageWidget/CustomImageWidget/Properties/AssemblyInfo.cs, DevMagazineSite/DevMagazine.Core/Properties/AssemblyInfo.cs, KendoBooksWidget/KendoBooksWidget/Properties/AssemblyInfo.cs, LICENSE.md, ListWidget/Properties/AssemblyInfo.cs, Precompilation/BootstrapPackage/BootstrapPackage/Properties/AssemblyInfo.cs, README.md, ReCaptcha/ReCaptcha/Properties/AssemblyInfo.cs, SimpleContentBlock/Properties/AssemblyInfo.cs, SingleDynamicContent/SingleDynamicContent/Properties/AssemblyInfo.cs
=> Updated readme, license and assembly info copyright year

AttributeRouting/BooksWidget/Properties/AssemblyInfo.cs, AuthorWidget/AuthorWidget/Properties/AssemblyInfo.cs, CustomImageWidget/CustomImageWidget/Properties/AssemblyInfo.cs, DevMagazineSite/DevMagazine.Core/Properties/AssemblyInfo.cs, KendoBooksWidget/KendoBooksWidget/Properties/AssemblyInfo.cs, LICENSE.md, ListWidget/Properties/AssemblyInfo.cs, Precompilation/BootstrapPackage/BootstrapPackage/Properties/AssemblyInfo.cs, README.md, ReCaptcha/ReCaptcha/Properties/AssemblyInfo.cs, SimpleContentBlock/Properties/AssemblyInfo.cs, SingleDynamicContent/SingleDynamicContent/Properties/AssemblyInfo.cs
=> Updated copyright info

AuthorWidget/AuthorWidget/MVC/Controllers/AuthorController.cs, AuthorWidget/readme.md, BoldlessContentBlock/readme.md, CustomImageWidget/CustomImageWidget/Mvc/Controllers/CustomImageController.cs, CustomImageWidget/README.md, CustomStylesContentBlock/readme.md, DynamicContentWidgetCustomDesigner/readme.md, SimpleContentBlock/Mvc/Controllers/SimpleContentBlockController.cs, SimpleContentBlock/readme.md, SingleDynamicContent/README.md, SingleDynamicContent/SingleDynamicContent/Mvc/Controllers/SingleDynamicContentController.cs, SingleDynamicContent/SingleDynamicContent/Mvc/Views/SingleDynamicContent/Default.cshtml
=> Docs feedback

SimpleContentBlock/Mvc/Views/SimpleContentBlock/custom-html-field-template.sf-cshtml
=> Fix contentblock style

EventsNextOccurrence/SitefinityWebApp/Mvc/Helpers/CustomEventHelpers.cs, EventsNextOccurrence/SitefinityWebApp/Mvc/Views/Event/Detail.EventDetails.cshtml, EventsNextOccurrence/SitefinityWebApp/Mvc/Views/Event/List.EventsList.cshtml, EventsNextOccurrence/readme.md, EventsUTCDates/SitefinityWebApp/Mvc/Helpers/CustomEventHelpers.cs, EventsUTCDates/SitefinityWebApp/Mvc/Views/Event/Detail.EventDetails.cshtml, EventsUTCDates/SitefinityWebApp/Mvc/Views/Event/List.EventsList.cshtml, EventsUTCDates/readme.md
Please review:
Do not merge before releaes of 9.1!
=> Events in utc

AttributeRouting/BooksWidget/BooksWidget.csproj, AttributeRouting/BooksWidget/app.config, AttributeRouting/BooksWidget/packages.config, AuthorWidget/AuthorWidget/AuthorWidget.csproj, AuthorWidget/AuthorWidget/packages.config, CustomImageWidget/CustomImageWidget/CustomImageWidget.csproj, CustomImageWidget/CustomImageWidget/app.config, CustomImageWidget/CustomImageWidget/packages.config, KendoBooksWidget/KendoBooksWidget/KendoBooksWidget.csproj, KendoBooksWidget/KendoBooksWidget/app.config, KendoBooksWidget/KendoBooksWidget/packages.config, ListWidget/ListWidget.csproj, ListWidget/packages.config, ReCaptcha/ReCaptcha/Properties/AssemblyInfo.cs, ReCaptcha/ReCaptcha/ReCaptcha.csproj, ReCaptcha/ReCaptcha/packages.config, SimpleContentBlock/SimpleContentBlock.csproj, SimpleContentBlock/packages.config, SingleDynamicContent/SingleDynamicContent/SingleDynamicContent.csproj, SingleDynamicContent/SingleDynamicContent/packages.config
=> Upgradeto9 1

DevMagazineSite/SitefinityWebApp/App_Data/Sitefinity/Configuration/DataConfig.config
Reverts Sitefinity/feather-samples#51
=> Revert "Setup the project to use locally attached .mdf file for easier initial setup"

ContentSelectorOnFrontend/Global.asax, ContentSelectorOnFrontend/Global.asax.cs, ContentSelectorOnFrontend/Mvc/Controllers/AppController.cs, ContentSelectorOnFrontend/Mvc/Scripts/App/app.js, ContentSelectorOnFrontend/Mvc/Views/App/Index.cshtml, ContentSelectorOnFrontend/README.md
=> Add new sample for using selector on frontend
